TBP/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.post_create, name='create_post'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment,
        name='add_comment'
    ),
    path(
        'follow/',
        views.follow_index,
        name='follow_index'
    ),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

TBP/tbp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

handler403 = 'core.views.permission_denied'
handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('about/', include('about.urls', namespace='about')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
    urlpatterns += (
        path('__debug__/', include(debug_toolbar.urls)),)

TBP/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class CreatedModel(models.Model):
    """Абстрактная модель. Добавляет дату создания."""
    created = models.DateTimeField(
        'Дата создания',
        auto_now_add=True
    )

    class Meta:
        abstract = True


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField()

    def __str__(self):
        return self.title


class Post(CreatedModel):
    text = models.TextField()
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts'
    )
    group = models.ForeignKey(
        Group,
        on_delete=models.SET_NULL,
        related_name='posts',
        blank=True,
        null=True
    )
    contact = models.EmailField

    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )

    def __str__(self):
        return self.text[:15]

    class Meta:
        ordering = ['-created']


class Comment(CreatedModel):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments'
    )
    text = models.TextField()


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following'
    )

TBP/posts/forms.py
from django import forms

from .models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image')
        labels = {'text': 'Текст поста.', 'group': 'Группа поста.'}
        help_texts = {'text': 'Нужно ввести текс поста. (обязательное поле)',
                      'group': 'Выберете группу. (необязательное поле)'}


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)
        labels = {'text': 'Текст комментария.'}
        help_texts = {'text': 'Нужно ввести текс комментария.'}

TBP/posts/views.py
from django.conf import settings
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator

from .models import Post, Group, User, Follow
from .forms import PostForm, CommentForm


@login_required
def post_create(request):
    """Создание нового поста, доступно авторизованному пользователю"""
    form = PostForm(request.POST or None, files=request.FILES or None)
    context = {'form': form}
    template = 'posts/create_post.html'
    if request.method == 'POST':
        if form.is_valid():
            text = form.cleaned_data['text']
            group = form.cleaned_data['group']
            image = form.cleaned_data['image']
            Post.objects.create(
                text=text, group=group, author=request.user, image=image
            )
            return redirect(f'/profile/{request.user.username}/')
        return render(request, template, context)
    return render(request, template, context)


@login_required
def post_edit(request, post_id):
    """Редактирование поста, доступно авторизованному автору поста"""
    post = get_object_or_404(Post, id=post_id)
    if post.author != request.user:
        return redirect(f'/posts/{post_id}/')
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post
    )
    context = {'form': form, 'is_edit': True}
    template = 'posts/create_post.html'
    if request.method == 'GET':
        return render(request, template, context)
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            return redirect(f'/posts/{post_id}/')
        return render(request, template, context)
    return redirect(f'/posts/{post_id}/')


@login_required
def add_comment(request, post_id):
    """Добавление комментариев, доступно авторизованному пользователю"""
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


def index(request):
    """Главная страница"""
    post_list = Post.objects.all()
    page_obj = create_page_obj(post_list, request)
    template = 'posts/index.html'
    context = {'page_obj': page_obj}
    return render(request, template, context)


def group_posts(request, slug):
    """Все посты выбранной группы"""
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.select_related('author')
    page_obj = create_page_obj(posts, request)
    template = 'posts/group_list.html'
    context = {
        'group': group,
        'page_obj': page_obj,
    }
    return render(request, template, context)


def profile(request, username):
    """Все посты выбранного автора"""
    user = get_object_or_404(User, username=username)
    post_list = Post.objects.filter(author=user)
    page_obj = create_page_obj(post_list, request)
    following = Follow.objects.filter(user=request.user.id).filter(author=user)
    template = 'posts/profile.html'
    context = {
        'author': user,
        'page_obj': page_obj,
        'following': following,
    }
    return render(request, template, context)


def post_detail(request, post_id):
    """Подробная информация о посте"""
    post = get_object_or_404(Post, id=post_id)
    template = 'posts/post_detail.html'
    form = CommentForm()
    comments = post.comments.select_related('author')
    context = {
        'post': post,
        'form': form,
        'comments': comments
    }
    return render(request, template, context)


def create_page_obj(posts, request):
    """Пагинатор, создаваемый из листа постов"""
    paginator = Paginator(posts, settings.POSTS_IN_PAGE)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return page_obj


@login_required
def follow_index(request):
    """Страница постов авторов на которых подписан пользователь"""
    post_list = Post.objects.filter(author__following__user=request.user)
    page_obj = create_page_obj(post_list, request)
    template = 'posts/follow.html'
    context = {'page_obj': page_obj}
    return render(request, template, context)


@login_required
def profile_follow(request, username):
    """Подписка пользователя на автора"""
    author = get_object_or_404(User, username=username)
    if request.user != author:
        Follow.objects.get_or_create(user=request.user, author=author)
    return redirect('posts:profile', username=username)


@login_required
def profile_unfollow(request, username):
    """Отписка пользователя на автора"""
    author = get_object_or_404(User, username=username)
    Follow.objects.get(user=request.user, author=author).delete()
    return redirect('posts:profile', username=username)

TBP/templates/posts/create_post.html
{% extends "base.html" %}
{% block content %}
{% load user_filters %}
<title>
{% if is_edit %}
  Редактировать запись
{% else %}
  Добавить запись
{% endif %}
</title>
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          {% if is_edit %}
            Редактировать запись
          {% else %}
            Добавить запись
          {% endif %}
        </div>
        <div class="card-body">
          {% if form.errors %}
            {% for field in form %}
              {% for error in field.errors %}
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
            {% endfor %}
            {% for error in form.non_field_errors %}
              <div class="alert alert-danger">
                {{ error|escape }}
              </div>
            {% endfor %}
          {% endif %}
          <form method="post" enctype="multipart/form-data">
          {% csrf_token %}
          {% for field in form %}
            <div class="form-group row my-3"
              {% if field.field.required %}
                aria-required="true"
              {% else %}
                aria-required="false"
              {% endif %}
            >
              <label for="{{ field.id_for_label }}">
                {{ field.label }}
                  {% if field.field.required %}
                    <span class="required text-danger">*</span>
                  {% endif %}
              </label>
              <div>
                {{ field|addclass:'form-control' }}
                {% if field.help_text %}
                  <small id="{{ field.id_for_label }}-help" class=
                          "form-text text-muted">
                    {{ field.help_text|safe }}
                  </small>
                {% endif %}
              </div>
            </div>
          {% endfor %}
          <div class="d-flex justify-content-end">
            <button type="submit" class="btn btn-primary">
              {% if is_edit %}
                Сохранить
              {% else %}
                Добавить
              {% endif %}
            </button>
          </div>
          </form>
        </div>
      </div>
    </div>
</div>
{% endblock %} 

TBP/templates/posts/follow.html
{% extends 'base.html'%}
{% block content %}
  <title>Статьи избранных авторов</title>
  <h1>Статьи избранных авторов</h1>
  {% for post in page_obj %}
    {% include 'includes/post_frame.html' with show_group_link=True show_profile_link=True%}
  {% endfor %}
  {% include 'includes/paginator.html' %}
{% endblock %}

TBP/templates/posts/group_list.html
{% extends 'base.html'%}
{% block content %}
  <title>Записи сообщества: {{ group }}</title>
  <h1>{{ group }}</h1>
  <p>{{ group.description }}</p>
  {% for post in page_obj %}
    {% include 'includes/post_frame.html' with show_group_link=False show_profile_link=True%}
  {% endfor %}
  {% include 'includes/paginator.html' %}
{% endblock %}

TBP/templates/posts/index.html
{% extends 'base.html'%}
<!--{% load cache %}-->
{% block content %}
  <title>Последние обновления на сайте</title>
  <h1>Последние обновления на сайте</h1>
  {% include 'includes/switcher.html' %}
<!--  {% cache 20 index_page %}-->
    {% for post in page_obj %}
      {% include 'includes/post_frame.html' with show_group_link=True show_profile_link=True%}
    {% endfor %}
  {% include 'includes/paginator.html' %}
<!--  {% endcache %}-->
{% endblock %}

TBP/templates/posts/post_detail.html
{% extends 'base.html'%}
{% block content %}
  {% load thumbnail %}
  {% load user_filters %}
  <title>Пост: {{ post|truncatechars:30 }}</title>
  <h1>Пост: {{ post|truncatechars:30 }}</h1>
  <div class="row">
    <aside class="col-12 col-md-3">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          Дата публикации: {{ post.created|date:"d E Y" }}
        </li>
        {% if post.group %}
          <li class="list-group-item">
            Группа: {{ post.group }}
            <a href="{% url 'posts:group_list' post.group.slug %}">
              все записи группы
            </a>
          </li>
        {% endif %}
        <li class="list-group-item">
          Автор: {{ post.author.get_full_name }}
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-center">
          Всего постов автора:  <span >{{ post.author.posts.count }}</span>
        </li>
        <li class="list-group-item">
          <a href="{% url 'posts:profile' post.author %}">
            все посты пользователя
          </a>
        </li>
      </ul>
    </aside>
    <article class="col-12 col-md-9">
      {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}
      <p>{{post.text}}</p>
      {% if post.author == user %}
        <a class="btn btn-primary"
          href="{% url 'posts:post_edit' post.id %}">
          редактировать запись
        </a>
      {% endif %}
      {% if user.is_authenticated %}
        <div class="card my-4">
          <h5 class="card-header">Добавить комментарий:</h5>
          <div class="card-body">
            <form method="post" action="{% url 'posts:add_comment' post.id %}">
              {% csrf_token %}
              <div class="form-group mb-2">
                {{ form.text|addclass:"form-control" }}
              </div>
              <button type="submit" class="btn btn-primary">Отправить</button>
            </form>
          </div>
        </div>
      {% endif %}
      {% for comment in comments %}
        <div class="media mb-4">
          <div class="media-body">
            <h5 class="mt-0">
            <a href="{% url 'posts:profile' comment.author.username %}">
              {{ comment.author.username }}
            </a>
            </h5>
            <p>
              {{ comment.text }}
            </p>
          </div>
        </div>
      {% endfor %}
    </article>
  </div>
{% endblock %}

TBP/templates/posts/profile.html
{% extends 'base.html'%}
{% block content %}
  <title> {{ author.get_full_name }} профайл пользователя</title>
  <h1>Все посты пользователя: {{ author.get_full_name }}</h1>
  <h3>Всего постов: {{ author.posts.count }} </h3>
  {% if following %}
    <a
      class="btn btn-lg btn-light"
      href="{% url 'posts:profile_unfollow' author.username %}" role="button"
    >
      Отписаться
    </a>
  {% else %}
    <a
      class="btn btn-lg btn-primary"
      href="{% url 'posts:profile_follow' author.username %}" role="button"
    >
      Подписаться
    </a>
   {% endif %}
  {% for post in page_obj %}
    {% include 'includes/post_frame.html' with show_group_link=True show_profile_link=False%}
  {% endfor %}
  {% include 'includes/paginator.html' %}
{% endblock %}